services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - huggingface-cache:/root/.cache/huggingface
    runtime: nvidia
    ports:
      - "8000:8000"
    ipc: host
    command: >
      --model openai/gpt-oss-120b
      --tensor-parallel-size 1
      --gpu-memory-utilization 0.95
      --max-model-len 131072
      --max-num-seqs 8
      --reasoning-parser openai_gptoss
      --async-scheduling
      --cuda-graph-sizes 2048
    restart: unless-stopped

volumes:
  # used to store huggingface models
  huggingface-cache:
