services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - huggingface-cache:/root/.cache/huggingface
    runtime: nvidia
    ports:
      - "8000:8000"
    ipc: host
    command: --model openai/gpt-oss-120b --max-model-len 4096
    restart: unless-stopped

volumes:
  # used to store huggingface models
  huggingface-cache:
