global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # --- Monitoring of the Base VLLM service ---
  - job_name: "base_vllm"
    metrics_path: /metrics
    static_configs:
      - targets: ["vllm_service:8000"]

