/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_attestedstream_free: (a: number, b: number) => void;
export const __wbg_ratlshttp_free: (a: number, b: number) => void;
export const attestedstream_attestation: (a: number) => [number, number, number];
export const attestedstream_closeWrite: (a: number) => any;
export const attestedstream_connect: (a: number, b: number, c: number, d: number, e: any) => any;
export const attestedstream_readable: (a: number) => any;
export const attestedstream_send: (a: number, b: number, c: number) => any;
export const mergeWithDefaultAppCompose: (a: any) => [number, number, number];
export const ratlshttp_attestation: (a: number) => [number, number, number];
export const ratlshttp_close: (a: number) => void;
export const ratlshttp_connect: (a: number, b: number, c: number, d: number, e: any) => any;
export const ratlshttp_fetch: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: any, i: number, j: number) => any;
export const ratlshttp_isReady: (a: number) => number;
export const js_get_collateral: (a: any, b: any) => any;
export const js_verify: (a: any, b: any, c: bigint) => [number, number, number];
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h1edcd8e466887c60: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h8305e36bc6ab8e87: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h97902348b896d545: (a: number, b: number, c: any) => any;
export const wasm_bindgen__convert__closures_____invoke__h856817fbb35ed73f: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hbafa2d432ab2eff4: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h8292ee2c618d9391: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h451fb53ae0a6ee3b: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h4f9595e0e4940b3f: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h66754e8be2e33a44: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h4de3c12abbdf6cad: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
