[project]
name = "cert-manager"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "cryptography>=43.0.0",
    "schedule==1.2.0",
    "dstack-sdk==0.5.3",
    "acme==2.7.4",
    "josepy==1.14.0",
]
